# Generated by Django 6.0.7 on 2026-07-13

import app.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_winchallenge_page_interval_seconds"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SpotifyOverlay",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_token", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(blank=True, default="Spotify-Overlay", max_length=120)),
                ("canvas_width", models.PositiveSmallIntegerField(default=720, validators=[django.core.validators.MinValueValidator(240), django.core.validators.MaxValueValidator(1920)])),
                ("canvas_height", models.PositiveSmallIntegerField(default=220, validators=[django.core.validators.MinValueValidator(120), django.core.validators.MaxValueValidator(1080)])),
                ("background_color", models.CharField(default="#121212", max_length=7, validators=[app.models.hex_color_validator])),
                ("background_opacity", models.PositiveSmallIntegerField(default=94, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ("corner_radius", models.PositiveSmallIntegerField(default=26, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(80)])),
                ("elements", models.JSONField(default=app.models.default_spotify_elements)),
                ("spotify_access_token", models.TextField(blank=True)),
                ("spotify_refresh_token", models.TextField(blank=True)),
                ("spotify_token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("spotify_connected_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("owner", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="spotify_overlays", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-updated_at", "-created_at")},
        ),
    ]
