# Generated by Django 6.0.7 on 2026-07-13 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_spotifyoverlay'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyoverlay',
            name='border_color',
            field=models.CharField(default='#1ed760', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, for example #14b8a6.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='spotifyoverlay',
            name='border_width',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
