# Generated by Django 6.0.7 on 2026-07-16 22:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_spotifyoverlay_border_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimerOverlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, default='Stream Timer', max_length=120)),
                ('label', models.CharField(blank=True, default='Starting soon', max_length=120)),
                ('mode', models.CharField(choices=[('countdown', 'Countdown'), ('stopwatch', 'Stopwatch')], default='countdown', max_length=20)),
                ('duration_seconds', models.PositiveIntegerField(default=300, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(359999)])),
                ('accumulated_seconds', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(359999)])),
                ('is_running', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('design_template', models.CharField(choices=[('minimal', 'Minimal'), ('glass', 'Glass'), ('neon', 'Neon')], default='glass', max_length=20)),
                ('background_color', models.CharField(default='#111827', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, for example #14b8a6.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('background_opacity', models.PositiveSmallIntegerField(default=86, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('text_color', models.CharField(default='#f8fafc', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, for example #14b8a6.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('accent_color', models.CharField(default='#8b5cf6', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, for example #14b8a6.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('border_color', models.CharField(default='#a78bfa', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, for example #14b8a6.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('border_width', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)])),
                ('corner_radius', models.PositiveSmallIntegerField(default=24, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(64)])),
                ('overlay_width', models.PositiveSmallIntegerField(default=520, validators=[django.core.validators.MinValueValidator(260), django.core.validators.MaxValueValidator(1200)])),
                ('overlay_height', models.PositiveSmallIntegerField(default=230, validators=[django.core.validators.MinValueValidator(140), django.core.validators.MaxValueValidator(600)])),
                ('label_text_size', models.PositiveSmallIntegerField(default=16, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(40)])),
                ('timer_text_size', models.PositiveSmallIntegerField(default=76, validators=[django.core.validators.MinValueValidator(36), django.core.validators.MaxValueValidator(160)])),
                ('show_progress', models.BooleanField(default=True)),
                ('shadow_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timer_overlays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
            },
        ),
    ]
