# Generated by Django 6.0.7 on 2026-07-22 10:19

import app.encrypted_fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def centralize_spotify_connections(apps, schema_editor):
    SpotifyConnection = apps.get_model('app', 'SpotifyConnection')
    SpotifyOverlay = apps.get_model('app', 'SpotifyOverlay')

    owner_ids = (
        SpotifyOverlay.objects.exclude(owner_id=None)
        .order_by()
        .values_list('owner_id', flat=True)
        .distinct()
    )

    for owner_id in owner_ids:
        overlays = list(
            SpotifyOverlay.objects.filter(owner_id=owner_id).order_by('-updated_at')
        )
        connected_overlays = [
            overlay
            for overlay in overlays
            if overlay.spotify_access_token or overlay.spotify_refresh_token
        ]
        source = max(
            connected_overlays or overlays,
            key=lambda overlay: (
                overlay.spotify_connected_at is not None,
                overlay.spotify_connected_at or overlay.updated_at,
            ),
        )
        connection = SpotifyConnection.objects.create(
            owner_id=owner_id,
            access_token=source.spotify_access_token,
            refresh_token=source.spotify_refresh_token,
            token_expires_at=source.spotify_token_expires_at,
            connected_at=source.spotify_connected_at,
        )
        SpotifyOverlay.objects.filter(owner_id=owner_id).update(connection=connection)

    for overlay in SpotifyOverlay.objects.filter(owner_id=None).iterator():
        if not (overlay.spotify_access_token or overlay.spotify_refresh_token):
            continue

        connection = SpotifyConnection.objects.create(
            access_token=overlay.spotify_access_token,
            refresh_token=overlay.spotify_refresh_token,
            token_expires_at=overlay.spotify_token_expires_at,
            connected_at=overlay.spotify_connected_at,
        )
        SpotifyOverlay.objects.filter(pk=overlay.pk).update(connection=connection)


def restore_overlay_tokens(apps, schema_editor):
    SpotifyOverlay = apps.get_model('app', 'SpotifyOverlay')

    for overlay in SpotifyOverlay.objects.exclude(connection_id=None).iterator():
        connection = overlay.connection
        overlay.spotify_access_token = connection.access_token
        overlay.spotify_refresh_token = connection.refresh_token
        overlay.spotify_token_expires_at = connection.token_expires_at
        overlay.spotify_connected_at = connection.connected_at
        overlay.save(
            update_fields=(
                'spotify_access_token',
                'spotify_refresh_token',
                'spotify_token_expires_at',
                'spotify_connected_at',
            )
        )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_timeroverlay'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', app.encrypted_fields.EncryptedTextField(blank=True)),
                ('refresh_token', app.encrypted_fields.EncryptedTextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('playback_cache', models.JSONField(blank=True, default=dict)),
                ('playback_cached_at', models.DateTimeField(blank=True, null=True)),
                ('playback_refresh_started_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spotify_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
            },
        ),
        migrations.AddField(
            model_name='spotifyoverlay',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overlays', to='app.spotifyconnection'),
        ),
        migrations.RunPython(
            centralize_spotify_connections,
            restore_overlay_tokens,
        ),
        migrations.RemoveField(
            model_name='spotifyoverlay',
            name='spotify_access_token',
        ),
        migrations.RemoveField(
            model_name='spotifyoverlay',
            name='spotify_connected_at',
        ),
        migrations.RemoveField(
            model_name='spotifyoverlay',
            name='spotify_refresh_token',
        ),
        migrations.RemoveField(
            model_name='spotifyoverlay',
            name='spotify_token_expires_at',
        ),
    ]
