# Generated by Django 6.0.7 on 2026-07-22 11:32

import app.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_centralize_spotify_connection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OverlayAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('font', 'Font')], max_length=12)),
                ('file', models.FileField(max_length=255, upload_to=app.models.overlay_asset_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overlay_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('kind', 'name', 'created_at'),
            },
        ),
        migrations.AddField(
            model_name='spotifyoverlay',
            name='background_asset',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'image'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.overlayasset'),
        ),
        migrations.AddField(
            model_name='spotifyoverlay',
            name='font_asset',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'font'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.overlayasset'),
        ),
        migrations.AddField(
            model_name='spotifyoverlay',
            name='logo_asset',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'image'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.overlayasset'),
        ),
        migrations.AddField(
            model_name='timeroverlay',
            name='background_asset',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'image'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.overlayasset'),
        ),
        migrations.AddField(
            model_name='timeroverlay',
            name='font_asset',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'font'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.overlayasset'),
        ),
        migrations.AddField(
            model_name='timeroverlay',
            name='logo_asset',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'image'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.overlayasset'),
        ),
        migrations.AddField(
            model_name='winchallenge',
            name='background_asset',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'image'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.overlayasset'),
        ),
        migrations.AddField(
            model_name='winchallenge',
            name='font_asset',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'font'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.overlayasset'),
        ),
        migrations.AddField(
            model_name='winchallenge',
            name='logo_asset',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'image'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.overlayasset'),
        ),
        migrations.CreateModel(
            name='OverlayVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overlay_type', models.CharField(max_length=20)),
                ('overlay_id', models.PositiveBigIntegerField()),
                ('snapshot', models.JSONField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('reason', models.CharField(choices=[('created', 'Created'), ('manual', 'Saved manually'), ('autosave', 'Autosaved'), ('restore', 'Restored')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overlay_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
                'indexes': [models.Index(fields=['owner', 'overlay_type', 'overlay_id', '-created_at'], name='overlay_version_lookup')],
            },
        ),
    ]
