# Generated by Django 6.0.7 on 2026-07-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_overlayasset_spotifyoverlay_background_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyoverlay',
            name='font_family',
            field=models.CharField(choices=[('system', 'System default'), ('arial', 'Arial'), ('verdana', 'Verdana'), ('trebuchet', 'Trebuchet MS'), ('georgia', 'Georgia'), ('times', 'Times New Roman'), ('courier', 'Courier New')], default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='timeroverlay',
            name='font_family',
            field=models.CharField(choices=[('system', 'System default'), ('arial', 'Arial'), ('verdana', 'Verdana'), ('trebuchet', 'Trebuchet MS'), ('georgia', 'Georgia'), ('times', 'Times New Roman'), ('courier', 'Courier New')], default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='winchallenge',
            name='font_family',
            field=models.CharField(choices=[('system', 'System default'), ('arial', 'Arial'), ('verdana', 'Verdana'), ('trebuchet', 'Trebuchet MS'), ('georgia', 'Georgia'), ('times', 'Times New Roman'), ('courier', 'Courier New')], default='system', max_length=20),
        ),
    ]
