# Generated by Django 6.0.7 on 2026-07-24 13:52

import app.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_spotifyoverlay_font_family_timeroverlay_font_family_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreOverlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_family', models.CharField(choices=[('system', 'System default'), ('arial', 'Arial'), ('verdana', 'Verdana'), ('trebuchet', 'Trebuchet MS'), ('georgia', 'Georgia'), ('times', 'Times New Roman'), ('courier', 'Courier New')], default='system', max_length=20)),
                ('public_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, default='Score HUD', max_length=120)),
                ('canvas_width', models.PositiveSmallIntegerField(default=960, validators=[django.core.validators.MinValueValidator(320), django.core.validators.MaxValueValidator(1920)])),
                ('canvas_height', models.PositiveSmallIntegerField(default=240, validators=[django.core.validators.MinValueValidator(140), django.core.validators.MaxValueValidator(1080)])),
                ('background_color', models.CharField(default='#0f172a', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, for example #14b8a6.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('background_opacity', models.PositiveSmallIntegerField(default=72, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('border_color', models.CharField(default='#38bdf8', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, for example #14b8a6.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('border_width', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('corner_radius', models.PositiveSmallIntegerField(default=28, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(80)])),
                ('allow_negative_scores', models.BooleanField(default=False)),
                ('elements', models.JSONField(default=app.models.default_score_elements)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('background_asset', models.ForeignKey(blank=True, limit_choices_to={'kind': 'image'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.overlayasset')),
                ('font_asset', models.ForeignKey(blank=True, limit_choices_to={'kind': 'font'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.overlayasset')),
                ('logo_asset', models.ForeignKey(blank=True, limit_choices_to={'kind': 'image'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.overlayasset')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_overlays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ScoreParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-99999), django.core.validators.MaxValueValidator(99999)])),
                ('accent_color', models.CharField(default='#38bdf8', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, for example #14b8a6.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_asset', models.ForeignKey(blank=True, limit_choices_to={'kind': 'image'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.overlayasset')),
                ('overlay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='app.scoreoverlay')),
            ],
            options={
                'ordering': ('sort_order', 'created_at', 'pk'),
            },
        ),
    ]
