"""Public view facade grouped by feature modules."""

# These module aliases preserve existing patch/import paths for integrations and tests.
from django.utils import timezone

from app import spotify_api
from app.views.common import overlay_asset_file
from app.views.dashboard import (
    overlay_asset_upload,
    overlay_dashboard,
    overlay_import,
    overlay_version_restore,
)
from app.views.pages import about, demo, home, robots_txt, signup, sitemap
from app.views.spotify import (
    spotify_autosave,
    spotify_callback,
    spotify_connect,
    spotify_create,
    spotify_delete,
    spotify_disconnect,
    spotify_duplicate,
    spotify_export,
    spotify_list,
    spotify_manage,
    spotify_overlay,
    spotify_overlay_state,
    spotify_renew_obs_link,
)
from app.views.timer import (
    timer_autosave,
    timer_control,
    timer_create,
    timer_delete,
    timer_duplicate,
    timer_export,
    timer_list,
    timer_manage,
    timer_overlay,
    timer_overlay_state,
    timer_renew_obs_link,
)
from app.views.winchallenge import (
    winchallenge_autosave,
    winchallenge_create,
    winchallenge_delete,
    winchallenge_duplicate,
    winchallenge_export,
    winchallenge_game_add,
    winchallenge_game_delete,
    winchallenge_game_rename,
    winchallenge_game_wins,
    winchallenge_list,
    winchallenge_manage,
    winchallenge_overlay,
    winchallenge_overlay_state,
    winchallenge_renew_obs_link,
)

__all__ = [
    "about",
    "demo",
    "home",
    "overlay_asset_file",
    "overlay_asset_upload",
    "overlay_dashboard",
    "overlay_import",
    "overlay_version_restore",
    "robots_txt",
    "signup",
    "sitemap",
    "spotify_api",
    "spotify_autosave",
    "spotify_callback",
    "spotify_connect",
    "spotify_create",
    "spotify_delete",
    "spotify_disconnect",
    "spotify_duplicate",
    "spotify_export",
    "spotify_list",
    "spotify_manage",
    "spotify_overlay",
    "spotify_overlay_state",
    "spotify_renew_obs_link",
    "timer_autosave",
    "timer_control",
    "timer_create",
    "timer_delete",
    "timer_duplicate",
    "timer_export",
    "timer_list",
    "timer_manage",
    "timer_overlay",
    "timer_overlay_state",
    "timer_renew_obs_link",
    "timezone",
    "winchallenge_autosave",
    "winchallenge_create",
    "winchallenge_delete",
    "winchallenge_duplicate",
    "winchallenge_export",
    "winchallenge_game_add",
    "winchallenge_game_delete",
    "winchallenge_game_rename",
    "winchallenge_game_wins",
    "winchallenge_list",
    "winchallenge_manage",
    "winchallenge_overlay",
    "winchallenge_overlay_state",
    "winchallenge_renew_obs_link",
]
